{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "terraform-parse.fullname" . }}
  labels:
    {{- include "terraform-parse.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "terraform-parse.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: {{ .Values.metrics.scrapePort }}
      interval: {{ .Values.metrics.interval }}
      path: {{ .Values.metrics.path }}
{{- end }}

